### ISSUE TITLE
Blog post link is incorrect. 

### ISSUE THREAD

**Issue by Callindrill** [OctopusDeploy/PowerShell-IIS-Examples#2]
The link at the top of the code page is to "https://octopus.com/blog/powershell-iis", but I believe it should be to "https://octopus.com/blog/iis-powershell".

**Comment by matt-richardson** [comment]
Hi @Callindrill - thanks for getting in touch!

I'm not sure where you mean when you say "the code page"? I've searched, but I cant find that anywhere?

**Comment by Callindrill** [comment]
If you click on the github header [Code](https://github.com/OctopusDeploy/PowerShell-IIS-Examples), it says in the description "Examples showing how to do everything with IIS and PowerShell https://octopus.com/blog/powershell-iis", but I believe it should be "Examples showing how to do everything with IIS and PowerShell https://octopus.com/blog/iis-powershell"

**Comment by matt-richardson** [comment]
Ahh - figured out where you mean now! 
Thanks for letting us know - I've updated it.
